stages:
  primary_source_check:
    cmd: python stages/00_external_dependency.py
    outs:
      - download/data-links.txt
  
  download:
    cmd: python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download/01_download

  process:
    cmd: python stages/02_convert.py
    deps:
      - stages/02_convert.py
      - download/01_download
    outs:
      - brick
